apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
    component: app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
